### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [denis-shvetcov/BackgammonMVC#1]
Будем считать, что модель вы выделили, хотя `Check` у Вас не чисто модельный класс. Осталось написать тесты для модели.

**Comment by denis-shvetcov** [comment]
А что необходимо протестировать? Одну партию?

вс, 24 мая 2020 г. в 06:20, Maxim Petrov <notifications@github.com>:

**Comment by maximpetrov** [comment]
В идеале да, чтобы проверить, в том числе, и выбрасывание в конце раунда. Но, подозреваю, это будет достаточно трудоёмко, так что протестируйте хотя бы начало партии с разными ситуациями: выпадение дубля, невозможность встать на чужую фишку, возможность встать на свою и т.д.

**Comment by denis-shvetcov** [comment]
А можно сделать метод, в который я сам буду устанавливать значения кубиков?
Просто я иначе не знаю, как тестировать

пн, 25 мая 2020 г., 15:04 Maxim Petrov <notifications@github.com>:

**Comment by maximpetrov** [comment]
Да, мы же с Вами так и договаривались. Только сделайте его package private. Ну или, если хотите более честно протестировать, то посмотрите на [Mockito](https://site.mockito.org/), который позволяет подменять методы в тестах (тогда нужно будет вынести генерацию значений кубиков в отдельный метод).

**Comment by denis-shvetcov** [comment]
Хорошо, спасибо.

пн, 25 мая 2020 г. в 16:00, Maxim Petrov <notifications@github.com>:

**Comment by denis-shvetcov** [comment]
Максим Алексеевич, я сделал тесты.

пн, 25 мая 2020 г. в 16:00, Maxim Petrov <notifications@github.com>:

**Comment by maximpetrov** [comment]
Пара мелких замечаний:
1. Не очень-то красиво использовать `Map.Entry` в качестве пары. Лучше в таких случаях использовать `Pair` из `javafx.util` или, если в проекте не используется `javafx`, то написать такой класс самому. А вообще здесь нет причин возвращать пару, ведь значения кубиков не зависят друг от друга. Поэтому лучше будет просто сделать метод для генерации одного значения и вызывать его для каждого кубика.
1. Нет никаких причин делать полями локальные переменные в тестах.

**Comment by denis-shvetcov** [comment]
То есть нужно сделать два метода и два списка со значениями?

ср, 27 мая 2020 г., 17:11 Maxim Petrov <notifications@github.com>:

**Comment by maximpetrov** [comment]
Нет, один метод, а в тестах один список с чередующимися значениями для первого и второго кубиков

**Comment by denis-shvetcov** [comment]
У меня поле Player используется в вспомогательном методе. То есть если я
убираю поля, то мне нужно Player передать в метод?

ср, 27 мая 2020 г., 17:11 Maxim Petrov <notifications@github.com>:

**Comment by maximpetrov** [comment]
Да, лучше его передавать параметром.

**Comment by denis-shvetcov** [comment]
Я исправил тесты.

**Comment by maximpetrov** [comment]
Принято
